SELECT
    no__de_cedula,
    numero_asociado,
    email,
    email_bncr,
    estado_asociado,
    con_ahorros,
    tiene_economias,
    tiene_ahorro_navideno,
    tiene_plan_fin_de_ano,
    tiene_ahorro_fondo_de_inversion,
    tiene_ahorro_plan_vacacional,
    tiene_ahorro_plan_aguinaldo,
    tiene_ahorro_plan_bono_escolar,
    tiene_ahorro_con_proposito,
    tiene_ahorro_plan_futuro,
    con_creditos,
    case when sobre_capital_social='no' then ahorros_credito else sobre_capital_social end as sobre_capital_social,
    case when adelanto_de_pension_sf = 'no' then adelanto_de_pension_pf else adelanto_de_pension_sf end as adelanto_de_pension,
    consumo_personal,
    salud,
    especiales_al_vencimiento,
    facilito,
    --vehiculos_no_usar,
    --credito_refinanciamiento,
    case when refundicion_de_pasivos = 'no' then refuncion_ii else refundicion_de_pasivos end as refundicion_de_pasivos,
    vivienda_patrimonial,
    case when credito_capitalizable = 'no' then 
        (case when capitalizable_2 ='no' then capitalizable_3 else capitalizable_2 end) else credito_capitalizable end as credito_capitalizable,
    tecnologico,
    credifacil,
    vivienda_cooperativa,
    --vivienda_adjudicados,
    multiuso,
    deuda_unica,
    vivienda_constructivo,
    case when credito_compra_vehiculos = 'no' then credito_vehiculos_seminuevos else credito_compra_vehiculos end as credito_compra_vehiculos,
    con_back_to_back,
    tiene_seguros,
    apoyo_funerario,
    seguro_su_vida,
    --funeraria_polini,
    poliza_colectiva,
    --plan_medismart,
    --poliza_vivienda,
    tiene_cesantia,
    --tiene_certificados,
    encargado
from update_contacts_hs